//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.status = new HashSet<status>();
        }
    
        public string rollNumber { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string bloodGroup { get; set; }
        public string imagePath { get; set; }
    
        public virtual ICollection<status> status { get; set; }
    }
}
